import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";
import "./globals.css";
import theme from "../../styles/theme";
import { ThemeProvider } from "@mui/material/styles";
import { CartProvider } from "./components/CartContext";

const redHatText = Red_Hat_Text({
  weight: ["400", "500", "700"], // 400: Regular, 500: Medium/SemiBold, 700: Bold
  subsets: ["latin"],
  variable: "--font-redhat-text",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${redHatText.variable} antialiased`}>
        <ThemeProvider theme={theme}>
          <CartProvider>{children}</CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
